main: io.github.nosequel.portage.bukkit.PortagePlugin
version: 1.0-SNAPSHOT
name: Portage
author: NoSQL
website: vapor.rip
description: Portage is a well-optimized multi-purpose network core utilizing MongoDB and Redis